const HTTP_STATUS_CODE = {
  SUCCESS: 200,
  CREATED_SUCCESSFULLY: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

module.exports = {
  HTTP_STATUS_CODE,
};
