const HTTP_STATUS_CODE = {
  SUCCESS: 200,
  CREATED_SUCCESSFULLY: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

const DEFAULT_PAGE_START = 0;

const DEFAULT_PAGE_SIZE = 10;

module.exports = {
  HTTP_STATUS_CODE,
  DEFAULT_PAGE_START,
  DEFAULT_PAGE_SIZE
};
